export const ADD_MEASURE = "ADD_MEASURE";
export const ADD_SPECIES_COUNT = "ADD_SPECIES_COUNT";
export const RESET_MEASURE = "RESET_MEASURE";
export const RESET_SPECIES_COUNT = "RESET_SPECIES_COUNT";
export const SET_CONTROL = "SET_CONTROL";
export const SET_TRACKER = "SET_TRACKER";
